### PR TITLE
I played around with the notebook a bit

### PR DESCRIPTION
**Pull request by dfm**
Here are my updates. It's still slow, but it looks like everything is pretty well converged now. It's mostly slow because of the covariance between `b_1` and `ecc_1`:

download-16

This could probably be fixed by parameterizing in terms of the approximate duration or something, but it's a bit tricky to do that properly *and* have reasonable priors on all the parameters. It would be worth thinking about this some more.

Note: Make sure that you're running at least v0.1.2 of exoplanet because I fixed a few bugs that might affect this fit.

### CODE REVIEW

**Comment by dfm** [comment]
PS: of course omega is part of that covariance too:

download-17

And here are the actual parameters that are being sampled:

download-18

Any non-affine covariances are tough for the sampler...

**Comment by dfm** [comment]
I switched to fitting in `logror` and `b` directly instead of in the joint space and it looks much better! It takes only ~5 hours instead of >12 hours.

**Comment by mrtommyb** [comment]
Ok, great. Good to know.

**Comment by dfm** [comment]
This pull request has the updated notebook. Take a look!

**Comment by mrtommyb** [comment]
Thanks for looking into this. It is really useful. Changing to ror/b sampling seems to really improve things. Before you pushed this, I played around with sampling e^0.5sinw and e^0.5cosw, but I didn't see a huge improvement.

**Comment by dfm** [comment]
Yeah - that parameterization won't generally help because you're already
using a better parameterization for omega with the Angle distribution.

On Thu, Dec 20, 2018 at 1:49 PM Tom Barclay <notifications@github.com>
wrote:

> Thanks for looking into this. It is really useful. Changing to ror/b
> sampling seems to really improve things. Before you pushed this, I played
> around with sampling e*0.5sinw and e*0.5cosw, but I didn't see a huge
> improvement.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mrtommyb_l98-2D59-2Dtransitmodel_pull_1-23issuecomment-2D449004999&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=g84_1n7WlOgx1VZe3pM8191d8TUQ9i0pkF-p7HyDXc8&s=UjPsDJQ3A_ERGXCRC1TnkS0uOM-GzRZ7qUgQDAJirDE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAVYSpYG161wGFBONmLcNaSO4SMfgdxEks5u65VIgaJpZM4ZZ-2DSa&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=g84_1n7WlOgx1VZe3pM8191d8TUQ9i0pkF-p7HyDXc8&s=rcDmj709F34BW2RqKLJwgaMh5x76FhgXggbbYUOmq1Y&e=>
> .
>
-- 
Dan Foreman-Mackey
Associate Research Scientist
Flatiron Institute
http://dfm.io

**Pull request closed without merging**
